//! The test reference: the contig registry, the [`FastaBuilder`], and a frozen
//! real-GRCh38 default (the `const`s at the bottom of the file).
//!
//! **Frozen fixture.** Three things here are immutable because reference-derived
//! tests calibrate against them: the contig names and their order (they define the
//! `reference_sequence_id` every `read().at("chr1", ..)` resolves to), the embedded
//! sequences, and their soft-masked (lowercase) ranges. Renaming/reordering a
//! contig renumbers references under every test that names one; changing a
//! sequence byte shifts what every derived read sees. *Adding* a contig is allowed
//! but moves per-reference denominators, so do it deliberately.
//!
//! The default carries lowercase (soft-masked) stretches on purpose, so tests
//! exercise riker's case handling rather than assuming an all-uppercase reference.

// Builder methods return the builder or owned data; allow the "could be
// `#[must_use]`" lints rather than annotate each.
#![allow(clippy::must_use_candidate, clippy::return_self_not_must_use)]

use std::fs::File;
use std::io::{self, BufReader};
use std::path::Path;
use std::sync::OnceLock;

/// The default reference contigs, in `reference_sequence_id` order.
pub const DEFAULT_CONTIGS: &[&str] = &["chr1", "chr2"];

/// Resolve a contig name to its `reference_sequence_id` in the default reference.
///
/// # Panics
/// Panics if `name` is not one of [`DEFAULT_CONTIGS`]. A test needing other
/// contigs should build an explicit reference/builder with its own contig set.
pub fn default_contig_id(name: &str) -> usize {
    DEFAULT_CONTIGS.iter().position(|&contig| contig == name).unwrap_or_else(|| {
        panic!("unknown contig {name:?}; the default reference has {DEFAULT_CONTIGS:?}")
    })
}

/// Builds an in-memory reference of named contigs and writes it as FASTA + `.fai`.
///
/// Doubles as the byte source that `read()` derives matching bases from, so it
/// both writes the `--reference` file a command needs and answers `bases()`.
#[derive(Clone)]
pub struct FastaBuilder {
    contigs: Vec<(String, Vec<u8>)>,
}

impl FastaBuilder {
    /// An empty reference.
    pub fn new() -> Self {
        Self { contigs: Vec::new() }
    }

    /// The frozen default reference: real GRCh38 slices relabeled to local 1-based
    /// coordinates (`chr1` ≈ 10 kb GC-rich, `chr2` ≈ 12 kb AT-rich), with a few
    /// soft-masked stretches. See the `const`s at the bottom of the file.
    pub fn hg38_mini() -> Self {
        Self {
            contigs: vec![
                ("chr1".to_string(), CHR1_SEQUENCE.to_vec()),
                ("chr2".to_string(), CHR2_SEQUENCE.to_vec()),
            ],
        }
    }

    /// Add a contig with an explicit sequence.
    pub fn contig(mut self, name: impl Into<String>, sequence: impl Into<Vec<u8>>) -> Self {
        self.contigs.push((name.into(), sequence.into()));
        self
    }

    /// Add a contig whose sequence is `motif` tiled `times` times (fgbio-style).
    pub fn repeat(mut self, name: impl Into<String>, motif: &[u8], times: usize) -> Self {
        self.contigs.push((name.into(), motif.repeat(times)));
        self
    }

    /// The reference bases for `contig` over `[start, start + len)` (1-based
    /// `start`), padded with `A` past the contig end. Empty if the contig is
    /// unknown. Bases are returned as stored, so soft-masked regions come back
    /// lowercase.
    pub fn bases(&self, contig: &str, start: usize, len: usize) -> Vec<u8> {
        let Some((_, sequence)) = self.contigs.iter().find(|(name, _)| name.as_str() == contig)
        else {
            return Vec::new();
        };
        let begin = start - 1;
        (begin..begin + len).map(|i| sequence.get(i).copied().unwrap_or(b'A')).collect()
    }

    /// The contigs as `(name, length)`, for header/sequence-dictionary construction.
    pub fn dict(&self) -> Vec<(String, usize)> {
        self.contigs.iter().map(|(name, sequence)| (name.clone(), sequence.len())).collect()
    }

    /// Write the reference as FASTA at `path` plus its `.fai` index at `<path>.fai`.
    ///
    /// # Errors
    /// Returns an error if either file cannot be created or written.
    pub fn write_fasta(&self, path: &Path) -> io::Result<()> {
        use noodles::fasta;

        // Write the FASTA wrapped at 60 bases/line via the noodles writer.
        let mut writer =
            fasta::io::writer::Builder::default().set_line_base_count(60).build_from_path(path)?;
        for (name, sequence) in &self.contigs {
            let definition = fasta::record::Definition::new(name.as_str(), None);
            let record =
                fasta::Record::new(definition, fasta::record::Sequence::from(sequence.clone()));
            writer.write_record(&record)?;
        }
        drop(writer);

        // Build the `.fai` by indexing the just-written file, so noodles owns the byte-offset
        // and line-width arithmetic (the same write-then-index pattern VcfBuilder uses).
        let mut indexer = fasta::io::Indexer::new(BufReader::new(File::open(path)?));
        let mut records = Vec::new();
        while let Some(record) = indexer.index_record().map_err(io::Error::other)? {
            records.push(record);
        }
        let mut fai_path = path.as_os_str().to_owned();
        fai_path.push(".fai");
        fasta::fai::fs::write(fai_path, &fasta::fai::Index::from(records))
    }

    /// Write the reference to a temporary `.fa` (plus its `.fai` at `<path>.fai`)
    /// and return the handle, which deletes both on drop. For commands that take a
    /// `--reference` path.
    ///
    /// # Errors
    /// Returns an error if the temp file cannot be created or written.
    pub fn to_temp_fasta(&self) -> io::Result<tempfile::NamedTempFile> {
        let tmp = tempfile::NamedTempFile::with_suffix(".fa")?;
        self.write_fasta(tmp.path())?;
        Ok(tmp)
    }
}

impl Default for FastaBuilder {
    fn default() -> Self {
        Self::new()
    }
}

/// The frozen default reference, built once and shared. Reads derive their bases
/// from this unless given another via `read().matching_ref(..)`.
pub(crate) fn default_reference() -> &'static FastaBuilder {
    static DEFAULT: OnceLock<FastaBuilder> = OnceLock::new();
    DEFAULT.get_or_init(FastaBuilder::hg38_mini)
}

// ─── Frozen GRCh38 slices ─────────────────────────────────────────────────────
//
// Real GRCh38 sequence relabeled to local 1-based coordinates, so a read at
// `chr1:100` derives its bases from offset 100 of `CHR1_SEQUENCE`. FROZEN — see the
// module docs; changing a byte or a masked range shifts what every derived test
// sees.
//
// Provenance: GRCh38_full_analysis_set_plus_decoy_hla
//   chr1 = chr1:1,000,001-1,010,000 (10,000 bp, GC 60.4%)
//   chr2 = chr2:1,000,001-1,012,000 (12,000 bp, GC 38.1%)
// Soft-masked to lowercase (0-based, half-open into the slice) to mimic a
// repeat-masked reference: chr1 [2000,2500) and [6000,6300); chr2 [1000,1400).
#[rustfmt::skip]
const CHR1_SEQUENCE: &[u8] = b"\
    GTGGAGCGCGCCGCCACGGACCACGGGCGGGCTGGCGGGCGAGCGGCGAGCGCGCGGCGATCCGAGCCCCTAGGGCGGAT\
    CCCGGCTCCAGGCCCGCGCGCGCCTCAGGCCGTTTCCCTATTTAAGGCCTCGCCGCCGCGGGGTGTGTGAACCCGGCTCC\
    GCATTCTTTCCCACACTCGCCCCAGCCAATCGACGGCCGCGCTCCTCCCCCGCTCGCTGTCAGTCACGCCTCGGCTCCGG\
    GCGCGGCCTCCGCGGGCGACAATGGCATGCGGGGCCCCCGCCCGCGCCCCCCTCCGACACCGCTGGGGACAGGGCCGGGT\
    GATCCCGCGCTCCCCGATGCAGCCGGGGCCGAGCAACGCGCCGGGAGGGGCCGCTGGGGGCGAACGGGGCCCGGGACCCC\
    CGGGGCTGGGCGGAGTCTCGGGGCTCACTCTCCCGCCCAGGGGGCCGGGAGCCGGGGCTGGACGGAGCTGGGGCTGTGGC\
    CGCGCGGGAAGTCGGGAAGGAAATTCCCCCAGTGGCGCAGGGTCCGGCGGCGCCGAGGGGTGGGCGAGCCTCGGTCTCGA\
    GCCTCTTGGCTTCCTCCGCCCGTCCCCACTCCGGTCCCGGTTTGGGCCCTGCTCGGTCTCCGAGTTTGATCCGACACCGG\
    CTCGGCCTCCGGGGGTCCCACCCTCAGGTGTGCGGCCTGGAGCACGGAGGGCTGCAGAAAGCCTTGGGAGCGACAGAGCC\
    GGGGGAAGGTCGGCGGCCGGGTCGGCAGGCGGGAGGGCGGAGTCAGCGGACGGCGAAGGGGCGCACGGGTGGCCCCGCAG\
    AGCAGGGCCGGTGATGGCGCGGGCCGGGCCGGACCACGAGGAGCAGAACGTGCGCGTGACGCGAGCGGGCTGGTGACGTC\
    ACCAGGCACCCGGGGCGATGACGCAAGCCTGCTGGGATGACGTCATGTGGCCCGTGTCGCCACGTGCTTCCAGGTGACCC\
    GCTGGCGAACTCAGCAGCAGCAAAGTGGGGCTCACAGAAAAATGAGGGGCCACTGTTAATATAACTGCAAAGGGGCAGGT\
    TGCGTAAAACAGGGCTGTGGTTATTTTCGTGTTTGCTGTTTTTATTTCGAATGCCGCTGCGGGGCACGTTGGTCCTTTCC\
    GCACTCGGGGTCCCCGGCGGCCTCACGCGTCCGTGCAGCGGAGGCTTCCTGAGCCCCCTGGAGAGCCTGGCCTGGGCCCG\
    GGTGTGGAGACCCTCCCGGGCTTTCAATCCGGGCAGGAGGCAGATGGCAGACTCAGCAGTCACGTAAGAGAACCGAATTA\
    GGTGGGTGGCCTGGGTGGACAAAAGCCTTCTTGACGCCGGGTGGTCCCAAAGGCTTCTGCGGGGTGGGGGGTCCTCAGGG\
    GGGAAGCCTCAAGGGAGGGCGTGGCATTCCCAGGGTGCGAAGGGGGCGCAGGGACGAGGGAGGTGGGGAGGGGGAGCTGG\
    GCCAGCGAGAACCGGGAGCTTCTGGTCGGGGAGGGAGTCGGGGAACTTTTTGGGGAGCTTTTCTGAGCCAGGGAGTCGGC\
    TGATTGGCAGGTTCGCCCCTGCCCGGGCACCTGGACCCAGGGTTTCTGTGCGGAAGCTTCCCCTCCCCTCGGACCCCACG\
    TCTAATCTGGCCCCAAGCAAAGTCCTGCGGCCCACGCGGGAAGGCGCCCTCTTCGCGGCGCTGACCCCGGCCCTCCGCGG\
    TGCCCCTGAGGCGCCCCCCACACCCCGCCGCTTGCACAGGGGCGCGGGGGGCTGCGAGGCCGGAGCGGGGGTGGCGCCCT\
    CTCCGCCGAGAGGCTGTCCGCGCCCCTCGCCGACTGGGGAAAGCCGCGGGGGCTGGGCGGGCGTCTCGGAGGTGGCCCCG\
    CGAGCACTTAAGCCCCGGCTCTCCTGCCCCGACCTCTCTGCGCGCGCCTCGGCGCTGGAGAGGCTCGGACCGGCCCCGTA\
    GCCCAGGAGGTGGTGTGGATGGTGTCCCCGTCCCGCGTCCCTCCCCGGCCTGAGCGCTGGGCCCGGGCGGGAAAGCCCGC\
    gagcgcccccagtggccgcagtcgccgccgcctcctgctgggggtcatcccaggggagctgccggcctgaatctccccag\
    cccctgggccccggcttgggaagaaatttgggggggctctgggcctcccccagtccctagacaggcagggagttcgggat\
    ggaaggaggagcctgaggatcgtttttatttattttttttttgtagagatggggatctccctatgttgcccaggctggtc\
    tcgaactcctggcccgagacgatgctcctgcctcggcctcccaacgtgctgggactacaggcgtgagtctcctccctgcc\
    aagcgtggctgggactgatcattccctcactggtttttagatgggctcacttcccctccttgtacctgttttctcatctg\
    taaaagggagctaacttttttttttttttttttttgaggcagcgtctcgctctgttgcccaggctggagtgcagtggcac\
    cacaacctttgcctcccgggTTCAAGCGATTCTCCTGCCTCAGCCTCCCAAGTAGCTGGGATTACAAGCATGTACCACCA\
    CGCCCGGCTAGTGTTTTGTATTTTTAGTAGAGATGGGGTTTCACTGTGTTGGCCAGGCTGGTCTTAATAGGAGATTCTAC\
    TTTTTTTTTTTCTTTTTTGAGACGGAGTTTCACTCTTGTCGCTCAGGCTGGAGTGCAGTGGCACGATCTGGGCTCACCAC\
    AACCTCTGCTTCCTGTATTCAAGCGATTCTCCTGCCTCAGCCTCTGGAGTAGCTGGGATTACAGGCGTGTGCCGCCACAC\
    CTGGCTAATTTTTGTATTTTTAGTAGAGATGTAGTTTCTCCATGTTGGTCAGGCTGGTCTCAAACTCCCCACCTCAGGTG\
    ATCCACGCACCTCAGCCTCCCAAAGTGCTGGGATTACAGGTGTGAGCCACCGTGCCTGGCCAGGAGATTCTACTTTTAAA\
    GCCACTGACGGCGTCCAACTCATAGTGAGCACCCACGCCCATCTGCCAGGGTTCCTGCCCCTGGGCAGCAGCTGGGGTCC\
    TTGCTGAGCAGAGGCAGGAGGGGCCACCAGCACTTGCCTCTGCTCTTCTGGAGAGGAAGAGACCCCCCTGCTCCCTGCCC\
    CCTGCCAGGGAGCCCACTCCAGGATCTCCGGGGACTGTGTTCCTCCCACCTTCTTTGCCACAGGACAGCTCCCATCTGTG\
    TGTCTGTCTCTCTGGGTCTGTGCCCTTGGCCTCTGATGGTCCCCTCCCTGCCTCTCGAATCTGGCCTCGATTTGTGGTAG\
    GGGCCTCAGGGTTCCTGAGGGCCTTGGGGTTCCCTTGCTCTGAGTGTGGGGGTGGATCCTGGGCTGCAGCCCAGGATGGT\
    GCCGACACCTGGGTTGGGGGCAGGTTGCGTTTTTCAGAGACGGCCGTGATAGTATCTCCCATCCCCATATCTTGAAATGC\
    CTTCTACATGAGACTCTGTGACAGTCTCAGCTGGGAAGAATGGGGTGTTTGGCAGGACATGACTTCTGAGGCTGACTTGG\
    AAGACGCCATGCGTACCTCGCTGTCCTGGGACAGTCGCTCTTGGAACCCAGCTGCCGTGCTGGGAGGGAGCACGCCCTGG\
    CCTCAAGGAGAGGCCCCGTGGAGGAATCAGCATTGGATTCCAGACTCCTGAGCAGCTTCCGGCGCAGGTCCCAGCGCGCC\
    CCGTTCCAAGGCTGCCCGCACACAGTAGGGTGGTTGCTGAGCGTGCTGTTTTGGGGTGGTTTGTGGTGCGGCACTCAAGA\
    CTGGAATAGTGGAGGTGGGCTGGGGCCCTGACCCAGGGAGAGTGACCCTTCCCTCCTCACCCCTGCTCCCTCCTCGCTGA\
    TCCCTTCCTCTCTTCCACAGAGGCAGAGGCTCAGCGACTTCCCCACCCCTCCCCCCCATCTAACGGGTGCTTCTTGGGAG\
    CCACTGAAATCCAGCCGACCTCCTGGCCCTGAGTGGGTCAAGCTCCAAATGGCGGGTGGCCCCGGGGCATCTGCACAGCC\
    CCCTGTTAGCTAAGGGGGGTGACTGATGAGGACATTCACACGCCAGTGGGGAGACTGTGGGGAAAACCGGGGTGTCTTCT\
    AGGCTGGACCTGGGGGGGCCTCAGCCTTGTTGGGGGGTCTCCTCACATTGGGCCACTGTGGCCGCACTCCATGACCACAG\
    CCAGTGTCCCCAAAAGGCCTGTGAGGTGCTGGCTGTGACCTCCCCTCCCAACCTCTGACCCAGAGGTGGCGGCTGCCATC\
    TCGCCACGGCCCTCAACACCCCCCTCACACACTGACTCCTGACATCAGAGACCTGTAGCCACCCCCTGCAGGTGGTCCTC\
    AGCATGGTCCCCAACTCCTGCCCAGGGCAGCGGGCTGTGCACTCAGGCAGCTGGGGCCAAAGCCACCGAGGAACCAAGGC\
    TGGGGTGGGGGTGGGTTTCTCTCCCGGAGAGCCGAGGTGGGCGCAGAGCTGTTCCTGGGTGTTTGCTGGGATTGTAGTGA\
    CAGAAGGCCAGGGCTGCAGGAATCCAGGCTGCCAGAGAGAGACCAGGACTCAGGCAGAAGCAGCAGCACCAGGCTGGTGC\
    CACTGCCACCCCACCTGCATGCCTTCTCAGCAGCGGTGGGAGCTGTGTCTCCAAGCAGGATGGTACTGGAGTCTCCCCAC\
    CCTGCCTGTCTGGGATGCCCTCCCAGCCTGTTCCTGCTCCCGGCAGGCGCTGCTTTTCTCTCTGCTGTACCAGGACGAGG\
    TGGGTGCCCTTGTCCCTCCTCACTGGCACTCCCAGACTGCTTTCCTTTTCCACCAAAACCACCCCCGCTTTGTGACCAGA\
    CCTCACTGTGTTGAAGTCATCGGCACCCCTTTCCTGCAGGAGGGGACACCTGCTCCCTGTCACTCTCCCGGCCATGCCTT\
    CAAAATCCACACCAGCAATTCTCCAACTTTGACTTCCTCTCTTTCAGGGGTCCTGTCCCCTCCCCACTTACCCCACTGGG\
    TCCTTTCTCCCAACTGCACCCCTCCACGGTCCAGCCTCTCCACTCTCTCTGCCCCCCTCCCAGCTCCCGCCTCTGCTGTC\
    CGCCAGCCCTGAGATCTCGGGCAGATGCACAGCCTGCATCTGCGGCTTCCTCCTCCCCTGTCTGTTCTCTCCTTATCAAG\
    AGAAGCCTATCTGGCCGGCCATTGTGTCTGCCCCTCACCCTCCCTCCTTCCTGTTCATGTGGGCAGACCACAGCCCGTGT\
    GGAATCCCTACCTTCTTGGTGGCTTAAGCACCACCTGCCTATTCTTTCCGTAGTGGGGATCAGGGCAGTGCCAGTGGCTT\
    CCTGGGGCCTCTCACAGCCTGCGGCCCTGGGCCAAGGTCAGCTGGGTGGGAAGGGCCCAAGGGTAGCCATGCTGGACACC\
    TGGGGCTGCTGTCCCTCAGCTGCCGGGCTCTCTGCCAGAGCCGTGCAGCCTGGAGTCCTACCCACTCTCAGTCAGCTTCC\
    TCCTAACACATGGCCAGCGTTCCAGGAGGGCGAAGTGGAAGCCTAGGGACTCTTGAGGCCAGGATCCAGAACGCACATAG\
    TAAAATCTCCACCACACTCCATCGGCCAAAGCAAGTCACAGCAGCCAGATTCCAGAGGAGTCGAAGCACACACTGACCCC\
    TCCTCCCCTCCACCGCCTGCCTCTGCCCTCCCCTCGCAGGGGCAGGGCTGCCTGATGAGCCCCCTGGGTTTATCTGCCCT\
    GCTGGCCCTGGGAAGGCTGGGATGAAAGTGTCATTTAGTGGCAGGGACTTTAGGGAGCCTGGTATGGTCAAGCCCTAGCC\
    CCCGCAGCAGTGCCCCCGCAGCAGTTCCCCCCGCAGCAGTGCCCCCAGGACAGCTGGGCCTGGGTCTCCAGTGGGTCGGA\
    GTTTTCTGAAGCCGGCCGTGGGTCGACCTCGCACCCGGTGACTGCCCCAGGCGGAGGGGCATGCGTGGCCCAGCGCGGGG\
    GCCCTGTCCGTGGCCGTGTGGGGTCAGGTGTCCGGCTCGGGGCTTCTGGGCCCCCTGCTCCCCAAAGGTGTGCAGCTCCC\
    gcgtcccctgccaggtcctttaggtctaagagggtccctcttgtccagcgcaccaggctccacgtacccccaacccctcc\
    ccagctgggtgcctccccctggctggaacggcagccctccctgctcatgggcctgcccctccactctatcctccctgacg\
    cagccagtggcatgcttctaacctgcagatgccctccccaggggccaagcccaccagacaccaggcaactctaagtggcc\
    cactgggtccactgtgtggagtgggaccctccgccctgtctcaggtcctgctgtcccaggAAGCCCTTACAGGGGGCTGC\
    AGCTGGGGGGTGACATGCCTGCCGAGTGGGTGGGGAGGCTCCGGCCCGGTAAGATGGGATCCAGCAGTGCGAGACTGTGG\
    CCCAGGTCAGATGGTGGCAGCTCGGCCTTCCTGGTCCCAGGTGGAGAGACAGGGTGAGGCTCCTCCCCATGGGATCTGGA\
    GGGGAGGGGCTGCCTGTGTAATCAGCCCAGCCTCGGACGTCAACAATCCATGTTTCTTAGGAAAGGCGGCCAACCCAGGG\
    TCTCCAGTGACACGTTTCCGGGTCATCATCCGGTGGCCACAGGGAATCACAGGCTCGGTGTGACTTTCTCAGAGCGCCAT\
    GGTGCCCCTGTGGGGTTTCCCAGCCCATCCTGTCCTGTGGGACAGGCAGAGGCCCAGCCGTGTCATCGGAGTGACCTTTG\
    AGCTCTAACCAAAGTCCACGTGTCATCAGGAGCCATGAGTCACTCAGGTGCCATCCAGGGCGGCGGCTGAGGAGTGGTGA\
    CTGGCCAGATGGGAAGGCGGGGAAGGGTCTGGATTTGAATGAGAGCGAGGGAGTGGGCTGCAGGCTGGTAGACTCCTCCA\
    GATGGATGAGGCCAGACCCCTGCAACAGCCATCCCGAGCAAGGCTCAAGCCTCCCTGAGAGTCCAGGGCGCCAAGTCAGC\
    CCTGCACCTGGCCCGGGCCTCGGACCCCGACGGGGCTCACCCACCTGAGATCACCCTGGCTCTGCGGGAAGGCAGGAAGC\
    TTTGGCATGATCCTCCACGGGCGAGGATCACGTAGAGACGTGTAGAGACGCGACGAAGCACGAAGACCCGTGTTTGACGG\
    GTTGCCAGGTGCCTACATCAGAGCTCATTAAATTACACATTAAATAGATGCACGTGTGTGTGTCAAGCTCCCCTAATTCA\
    AGTTGTAGAAAATCAGACTCAGAGTTCTTACACTCGGGGGTGTTTTAGCAGCTGCGCCTCAAGATTCTAAATTCAAACGC\
    ACACGGAATAAAACATTTCGGTTTATCGCCAGGCGCGGCGGCTCACACCTGCCATCCCAGCCCTTTGGGAGGCCGGGGTG\
    GGTGGATCACCTGAGGTCAGGAGTTGGAGACCAGCCTGGCCAACATGGTGAAACCCCGTCTCTACTAAAAATACAAAGAT\
    TAGCTGGGTGTGGTGGTGGGCGTCTGTAATCCCAGCTACTCGGGAGGCTGAGGCAGGAGAATCGCTTGAACCCGGGAGGT\
    AAAGGTTATGGTGAGCCAAGATCATGCCACTGCACTCTAGCCTGGGCAACAAGAGCAAACTCTGTCTCAAAAAGAAAAAG\
    AAAAGAAAAAAGAAAAAGTTTATTCCCAGTAAAACACGTTCAACTCTCCAGATCGTGGTGACATTTCCAGCTTGATGTGG\
    TAACGTGATTGTGAGCTTCAGGTATGACCTTCAGCATAAATACGTGTGCCATCTCCTGTGCAATTCTTTTTTTTTTTTTT\
    TTTTTTTTTTTTTTTTTTTTGAGACGGAGTCTCGCTCTGTCGCCCAGGCTGGAGTGCAGTGGCGGGATCTCGGCTCACTG\
    CAAGCTCCGCCTCCCGGGTTCACGCCATTCTCCTGCCTCAGCCTCCCAAGTAGCTGGGACTACAGGCGCCCGCCACTACG\
    CCCGGCTAATTTTTTGTATTTTTAGTAGAGACGGGGTTTCACCGTTTTAGCTGGGATGGTCTCGATCTCCTGACCTCGTG\
    ATCCGCCCGCCTCGGCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACCGCGCCCGGCTCCTGTGCAATTCTTACAGA\
    CCCAGCTTGGCTGTTCTCCAGTGTCTCCTTTGGGAGTTGTACCTGATTTTATTACCAGTTTTCATCTGAATCCACTGGGG\
    AATGGGACGATTTTGCTTTTGTTTCTTGGCCAGGAATCGCTTAATTCTGAAAGTCTGGTGAGAAGACACGGCGAGAATCG\
    GGGTCCAGCACAGATGATGGCGACAGCGGAGAAGGGAAGGTAAGGGAGGGGGCTCAAGCTTTTATCGTTATGGGACCTCC\
    TGTGTCTATTATGCTTTCTTCCATGATCTTTGTTAGTATGTTAATGACTTTGTTAATATATCCACACCTGCTTCCTTTTA\
    CTTAATATTTGTGTGGTATGCTTCTTTCCATTGCTTGATGTTCAAACTTGCTGTGTCTTTATGTTTCAGATGATTCTTGT\
    CTCTGGAAGCCACACAGAGCCAGTTGTTTGTTTTGTTTGTTTGTTTCTTTCTTTCTTTTTTTGAGACGGAGTTTCGTTCT\
    TGTCCCCCAGGCTGGAGTGCAATGGCACGATCTCGGCTCACTGCAACCTCCGCCTCCCAGGTTCAAGCAATTCTCCTGCC\
    TCAGCCTCCCAAGTAGCTGGGACTACAGGTGCCCACCACCACGCCGTACTCATTTTGCCTTTTTAGTAGAGACGGGGTTT\
    CACTGTGTTGGCCAGGCTGGTCTTGAACTCCTGACCTCAGGCGATTCACCCGCCTTGGCCTCCCAAAGTGCTGGGATTAC\
    AGGTGTGAGCCACCGCGCCCGGCGTTTTGTTTCATTTTTATTTTTGAGACACGGTCTTGCTCTGTCGCCCAGGCTGGAGT\
    GCAGTGTCGCAATCTCGGCTCACTGCATCCTCCGCCTCCCGGGTTCAAGCCATTCTCGTGCCTCAGCCTCCCGAGTAGCT\
    GGGACTGCAGGCGCCCACCACCACGCCCGGCTATTTTTTTTTTTAGAGGTGGGGTCTCACTATGTTGCCCAGGCTGGTCT\
    CAAACTCCCAGGCTCAAGCGATCCTCTAGGCTTTGCTTCCAAAGTGCTGAAATTACAGATGTGAGCCACCATCTGACAAT\
    CTTGGTCATTTAGTCCACATGAATTTTGGGCTTTTGGCCTGGAGAACTACGAGAGAATACATTTCTGTGGTGTGAAGTTT\
    AACACCCAGTTTGTGGTACATTGTTCAGCAACCCCAGGAAACTAAAGCAAGTGACTGCAGGTCTGGTCACCTTCCTCGGT\
    GCCTGTGCCTGGGGTTGGTTCTGTCGAAGCAGGAAGACAACTGGCAGAGATGGGATGAAGTAACCAAAAGGAAAGGAAGA\
    TTCTAGCACCGTACGTCAGCATTAAGAAATCAGGAAACGGGCCGGGCGCGGTGGCTCACGCCTGTAATCTCAGCACTTTG\
    GGAGGATGAGGTGGGCGGATCACGAGGTCAGGAGATCGAGACCATCCTGGGTAACACGGTGAAACCCCGTCTCTACTAAA\
    AATACAAAAAATTAGCCAAGCGTGGTGGTGGGCGCCTGTAGTCCCAGCTGCTCGGGAGGCTGAGGCAGGAGAATTGCTTG\
    AGCCCTGGAGGCGGAGCTTGCAGTGAGCTGAGATGGCACCACTGCACTCCAGCCTGGGCGACAGCAAGACTCCGTCTCAA\
    AAAAAAAAAAAAGAAAAGAAATCAGGAAACATATACCATGTTTAACAGGGCATCTAAAATGATAAAAATAAATAGAAAAT\
    CCTGGGTTTTTTGTTTGTTTTGCTTGGGTTTGGTTTGGTTTTGAGACAGGGTCTCGCTCTGTCACCCAGGCTGGAGTGCA\
    GTGGTGCGATCACAGCTCACTGCAGCCTCCACCTCCCGGGTTCAAGCTATCCTCCCACCTCAGCCTCCAAAGTAGCCAGG\
    ACTACAGGTGTGCGCCACCACGCCCGGCCAATTTTTTTATGTATTGCAGGGACAGGGTTTCACCATGTTGCCCAGGCTGG";
#[rustfmt::skip]
const CHR2_SEQUENCE: &[u8] = b"\
    TGGAAATAAAACAACCTGGTCCTGAATGATCGTGGGGTGAAAAATGCTATTAAGATGGAAAATTTTTAAATTTTCTTTAC\
    CTGAATGAAAATGGAGCTACAACATACCAAAATATCTGGGATACAGAAAAATAAGTGCTGAAATGAAGCTTTATAGCATT\
    AAATTTCTGCATGAAAAAATAGAAATATTACAAATTAACAACCTAACATTGCACATCAAGGAACCAGGAAAAGAAGAACA\
    AACCAAACCCAAAGCTAACAGAAGAAAATAAATAAAGATAAAAGCAAAACCAAATAAAATTGAGACCAAAAAAATCATAC\
    AAAGCATCATCAAAACAAAAAGTTGTTTCTTTGAAAGGATAAATTAAATTAATAGACCACTAGCTATATTGACCAAGAAA\
    AAAGATAAGATTTAAACAATCAGAAATGATAAATATGACACTACAACTGATATCACAGAAATACAAAAGATCCTCAGAGA\
    CTACTGTGAACATTTCTGTTCACACAGACTAGAAAACCTAGAGGAAATACATAAATTCTTGGAAATATACAACCTCTCAA\
    TATTGAACCAGGAAGAAATAGAAATCCTGAACAACCCAATAACTTATTAAGTTGAATAAATGATTTAAAATTCTAACCAA\
    AACAAGTCCAGGATCAGACAGTTTCACAGATAAATTATACTAGATGTACAAAGAAGAACTGGTACCAATCTTACTGAAAC\
    TATTTTAAAAAATGAGGAGGAAGGACTCATTTCTCACTCATTCTATGAAACCAGTATCATCATGATAAAAAAAACCTAGC\
    AAGAACACAACAAAAAAGAAAGCTACAGGCAAATATCATAGATGAACATAGATGCAAAATCCTCAAGAAAGTACTAGCAA\
    ATAAAATCCAGCAGCATGTCAAAAATGTGATCAAAATTTTATCATGATCAGATGAGTTTTAACTCCAGAAATGCAATGAA\
    GGTATATGCAAATCAACAAATGTGATTCGCCACGTAAACAaaaagtaaaaaccaaaaacatataatcatctcaatagatg\
    cagaagaagcattcaataaattccaacatcccttcataataaaaccctgaacaagctaggtattgaaggaacatacataa\
    aaataataagagccatgtatgagaaatgcacagtcaacatcatactgaatggacaaacaccaaaaacatgctcctaagag\
    ctggaacaagatgaagatgttcactctcacctctcctattcaacatagtactgaaagttttagccagatcagtcagtaaa\
    gagaaagacataaaagacatcccaattggaaaagaggatgtcaaattatctctgtttgctgatgatgtgatcttatacct\
    agaaaatcctcaagactctttcaaaagactcctatatttgAGAAATGAATTCAATAAAGTTTCAAGATAAAAATAAATGT\
    ACAAAAATCAGTAGCATTTTTATACAACAATAATGATCAAGCTGAGAACCAATTCAGGAAGTCAATTCCATGTACAATAG\
    CTACAATAAGTAAAATACCTAGGATTATATTTAACCAAGGAGGTAAAAGAATTCTACAAGAAAAACTATGAAGCACTGAT\
    GAAAGAAATCTTAGATGAAACAAACAAATGGAAAAACCTCCCTGGCTCATGGATTGAAAAAAATCAATATTATTAAAATA\
    ACCATACTACCCAAAGCAATCTAGAGATTCAGTGCAATTCTCACCAAAATATTAATATCATTTTTTAAAAGATTAGAAAA\
    AAAGTCCTAAAATCCATGTGGAACTAAAAAAGAGGCTGAATAGCCAAGCAGTTCTAAGTAAAAAGAACAAAGCTGGAGGT\
    ATCACATTACCTGACTTCAAATTATACTACAAGGCTATATTAACCAAAAGAGCATGGTCCTGATATAAAAATAGACATGT\
    AGATCAAGGAACAGAATAGAGAACCCAGACATAAAGCCACATACATACAGGCAACTGATCTTTTACAAAGTTGATGAAAA\
    CACACACTAATGTAAGGATACCCTATCCAAAAATGGTGCTGGGAAAATTGGATAGCCATATGCAGAAGAATTCAGCTGGA\
    TCCATAGCTCTCACCATATACGAAAGTTAACTCAAAATAAGTTAAAAATTTAAATATAACACCTGAAACTATAAAAAAAC\
    CAGAAGAAAATCTAGGAAAATCTCTTCTGGACATTGCCATGATCAAATAATTTATTACTAAGACCTCAAAAGCAAATGGA\
    AAACATCCCAAAAATAGACAAATTGAACTAAAATGCTTCTGCACAGTGAAAGACAAAATTGACATAGTGAACAGACAACT\
    TATAGAATGGGGGAAAATATTTGCAAACTGCATTTAGTGAGTAACTAATATCCAGAATCTACAAGGAATGCAAAAAACTC\
    AATAACAAAAGCAACCACTTAAAAGTAGGCAAAAGTAGGCAAAAGACATGAACATATATTTTTCAAAAGACAAACAAATG\
    GTTACAAGCATTTGAATTAATGCTGAACGACACTGATCATCACAGAAATGCAAATTAAAACCACAATGAGATACCGCCTT\
    ATACCAGTCAGAATAGCTATTATTAAAAATTAAAAACAGATGTGTATGAGGATGTGGAGAAAATACTTATCTATGGTTGG\
    TTGAAATATAAATAGAACAACCTCTATGAAAAAGGGTATGAATATTTCTCAAAAAAAAAAAAAACCTAAAAATAAAACTG\
    CCATTCAATCCAGCAATCCCATAAAGGATATATACCCAAAGGGAAAAAAATTATATCATTATATCAAAAAGATAGTTGTA\
    TGTTTACTGTGGCACTATTCACAGTAGCAAATATCTAGAATCAATGTGTTCTTCAATGAATGAATGACTAGGTAAAGAAA\
    ATGTTATATATATATATATATTTATATAGTCACCCATAAAAAAGAATACAATCTTGTCTTTTTCAGCAACATGGATGGAA\
    GTGGAGGTCATTATCTTAAACGAATTAACTCAGAAACAGCCAAATCCTGCATGTCCCTGCATGTTTCCACTTCCAAGTGA\
    GAGCTGAATAAAGTGTACACACAACCATAGTAGAATAATAGACCTGGAGACTCAGAAAGTGGGGAGGGTGGTAAGAGATG\
    AGAAATTACCTCATGGGCACAATGTAAACTCTCTGGCTGATAGCTACACTAAAAGCCTGCATGCACCACTACATGGTATA\
    TCCATGTAACAAAACTGCACACGTACCCCCTAAATCTATAAAAATAATTCAAAAAGAAAAAAATAATGGATTTGCACGAG\
    TATATGAATCTATTATGGGAGGATGACAGTGTATAGTCAAGAGTGTGGCCTGGAATTGGGTAAGGTGAGGGACGGAGGTT\
    TGCAAAGTGCATGTCTGGGTGACACAAGCCAGTGGCATCAGCTCAGGCATCAGCGGTGTCAGCCCCCAAACTCTGGACCC\
    AGTTGGAGGCTTCCATAATTAACAGGGAGCATCAAACATATTAACCAAGCATTCATCATGTCTAGACTTCATTACATATG\
    ACATTATGATTTCTATTGTATTGGAGTCTAGAGAGAGGCCCAGGATTTCTGTACACATTTGGACAGGCTTCCTTCCTTCT\
    GTCTTACCTTGGGTGCATTTGCCTGGCAGGTGAGAATGGTTAGGCAGCCAAGTGTTTCTGTGAGAACCTGTTCCAGTGAT\
    GTCCTAAGCAGCTATGAGTTTCGGAAGGAGCTGCTGTGACGATCTATTAATAGATGGTCCCTAATATGATGCACTTTTAA\
    GCATCACTCGTGTAGCTACTTGCTATTATTTCATTTTGAAATCTTTATTACTTCAGATTACACTTATGTAACATTGTTGA\
    AACATCATATTTTCTTTGTACATAAACTTTTTGTTATTTCTCAAAGAAGTAATTGTAATTTGCTAGGCTTCTCCCCTTTA\
    TTCCTTAATGTGTACTGTATTCTGGGGCTTCTGAAATCCCCATGCAAACTGAATGCTTAATTTAATACCTGTCATGACCT\
    GAATTACTTCATTTGGGAAGAGAGCTATTACAAAGCAGCTGTGATAAAAGGAGAATTTGCCAAATATTTATACCTATACA\
    GAATCCCCTAAACTGTGCAACCTATTTGGTTTTAATTCTATAAAAGAAGTTATACCATGTTTTATTCTTAATGATAGTGC\
    CTGACATGACTGTCCTGTGACAAAAACTAAATCATTAGTCCCTGTAACAGGAAGTCTATATTCATAAAACTCTTACAAGA\
    TAACACAGGAAAAGCCTGGTTTATGTTGGATATGATGATGACTTTTGATATGACATCAAAAGTACAATCCATGAAAGAAA\
    TAACTGCTAATTTAAAATTGAAGACTTCTGCTCTGCAAAAGACATTGTTAAGATAATGAAAAGACAAGCCAAAGACTTGT\
    AGAAAGTATTTGAAAAATAATCTCTGATAAATGGCTTGTACACAGGATATACAAAGAACTAAAACTCAACTACAAAACCT\
    TGAAGAACCCATTAAAACTTGGGCAAAACGCTTGAACAGACACCTCATGTAGATCTGCAGATGGCAGATAAGCATATGAG\
    GATGCTCAATGTCACATGTCAGGGAATTGCAAATTACAGCCGCAATGAGACAACCCTACACCACTGTTAGCTGGCTAAAA\
    TCCAAAACGCTGACAGCACCAGATGCTGGCAAGGATGTGGAGCGATGGGGACTCTCCTTCGTTGTGGGTGTGAATGCAAG\
    TATGGTGAAGTCATTTTGGAAGACAGTTTGGTGGTTTCTTACTTTGCTAAACATATTCTTAACATAGAACCTAGCAGTTG\
    TGCTCTCTGGACTTTACCCAAATGAATTGAAAACTTATGTACCCACACAAAAAACATGCAGAGATGTTAACAAAAGCATT\
    ATTTATTTGTTTATTTTATAATTATGTATAATTGTCAAAAACTGGAAGCAACCAAGATGTCCTTCAGAAGGTGAATGGAG\
    AAATAAACTATGGTTCATCCAGTCACTGTAATGTTATTCAACAGTAAAAAGAAATGAACTATCAAGCCACAAAAAAATGG\
    AGGAAATTTACATGCAAATTACTAAGAAAGAAGTCAATCTGAAAAGGCTGCAGACTGCATGATGCCAACTGTATGACCTG\
    TTGGAAAAGGCAGAACTCTAGAGACAGTAAAGAGATCATGGATTGTGGGGCGGGAGGGGTGAACAGGTGGAGCACCGAGG\
    ATGTTCAGGGCAGTGAAACTGAGTTGTATGATCCTGTAGTGGTGGACAGGTGTCATTATCTGTCTGTCCAAATCCACAGA\
    ATGCACAACACCTGGAGTGAACCTTGGTGTAAACCATGACTCTGGGTGACGAGGACATGTCCACGTAGGTTCACCAATGA\
    TAACAAATGCGCCACCTGGGGGATGTTGATAATGAAGGGGCTGTGCACATGTGGGGGCGGTGGGGGTACGTGAATTCTCT\
    GTACCGTCCTCGTCCTCTCAGTTTCTCTGTGAAGCTAAAACCCCTCTAAGAATGAAATCTATTTTAAAATATTAACGTTG\
    GAGCTGGGCACAGTGGCTCACACCTGTAATCCCAGCACTTTGGGAGGCTGAGGCGGGTGGATCGCCTGAGGTCAGGAGTT\
    TGAGACCACTCTGACCAACATGGAGAAACCTCGTCTCCACTAACAGTACAAAAATTAGCCAGGCGTGGTGACATGTGCCT\
    ATAGTCCCAGCTACTCAGGAGGCTGAGGCAGGGGAATTGCTTGAAGCTGGGAGGCGGAGGTTGCAGTGAGCCGAGATTGC\
    ACCATTGCACTCCAGCCTGGGCGACAGAGCAAGACTCTGCCTCAAAATATATATATATATATATATATATATATATATAT\
    ATATATATATATATATATATATATATATATATATAAACGTTGACATTGCTCTTGAGACTTTATTTTTATATTATTTAAAC\
    ATTGGATGAAAAATTTTACATGCCAACTGAATTATATGGAGGAAGCCAAGATAAATAATTAGCAATATAGTCTTCAGGGA\
    CATATGAGCAGAGTATTTGAAAACTCTGGAAATTGGAAATCATCATTCTCAGTAAACTATTGCAAGAACAAAAAACCAAA\
    CACCGCATATTCTCACTCATAGGTGGGAATTGAACAATGAGATCACATGGACACAGGAAGGGGAATATCACACTCTGGGG\
    ACTGTGGTGGGGTGGGGGGAGGGATAGCATTGGGAGATATACCTAATGCTAGATGACAAGTTAGTGGGTGCAGCGCACTA\
    GCATGGCACATGTATACATATGTAACTAACCTGCACAATGTGCACATGTACCTTAAAACTTAAGGTATAATTAAAAAAAA\
    GAAAAAAAATGCATTGATTATATACATATTAGTGAATATAACCTATAAAATATTAACCAGATATTAAATAAAGTAGAATT\
    TCAAAAAAAAAAGAAAATTCTATTAATACGTATTTGGATGCTAATCTTGTGTTTTGGTGAAAAATTCCTTTTTTATTTTG\
    AGTGGACCTCAGTATCATCATTTACTTAGAGAATTTACCGTTGTCTACTTTTAGTTATACTTTTCTGTATAGACTTGGCC\
    CGCCACATCCGTGGGTTCAACCAACTGTGGATGGAATGCATTTGAATAGAAAATGTGTCTGTACTTATGTATAGACTTTT\
    TCCTTGTCATTATTCCCTAAATAATATATTGTAACAGTGTTGTTATGGCATTTACATTGTGGTAGATAGAAGTAATCTGG\
    AGATGATTTAGAGTATGAGGGAGGGCCAGGCGCGGTGGCTCACGCCTGTAATGTCAGCAGTTTGGGAGGCTGAGATGGGT\
    GGATCACCTGAGGTCAGAAGATCGAGACCAGCCTGACCATCATGGTGAAACAAACACCCTTTCTACTAAAAGTACAATAT\
    TAGCCAGGCATGGTGACACATGCCTGTAATCCCAGCTACTAGAGAGGCTGAGGCAGGAGAATCGCTTGAACCTGGGAAGT\
    GAAAGTTTCAGTGAGCCGAGATTGTGCCACTGCACCCCAGCCTGGGCAACAGAGCGAAACTCCATCTCAAATAAATAAAT\
    AAATAAATAAATAAATAAATGTGTATATATATATGTATGTATAGGGGAGGAGGTGCATGGGTTTTTTGCAAATACTGCAC\
    CATTTTATATCAGGGACTTGAGTATGTGTGGGTTTGGGTATCTGGGGAGGTCCTGGAATCCATCCCCCACAGATCCCAAA\
    GGACACTGCATGACTCTCACACACACCCTAGTGAGAAGGACATTAGACAGGCGACCTGAGTTCTATGTTTTGGCCAATTC\
    CTGACCCACACGATCCTAGGCCATCATAAATCACGTCTCTAAACTTGTTACCTCATCGGTGGAGACACCTGGGTGTTGCC\
    AAGAGAAGTAGCAAAGGTTTTGGTGTTTGATGGACTCACATTTAGACCTGACTTGCCCTTTCCAGCTGAGGATGTTGGGC\
    AGGAAACAAAACTTCCCTGAGCCTCAGTTTCCACAGTAAAAATGGCATTAATTATATGTGTTACACATTGTTGTGAAGAT\
    TGAAGATGATGTCTTTAAATCACCCACCACAAGGCATAGTAGACAAGGTGAGCAAGGAATTTTCTGAGTAAATGTAGCAT\
    TACCTCCTAAGACTGCTTCTCTTAAACGATTTCCTAAAAATCATCATAGAATGATGTACTATATGGGAGAGCACTCAGTA\
    AGCGTTCAGGTCTATAGAAAAAGATGCACATCCCTTGTATTGAGTTATAAACTCAGTGGACAATATACCTTAGAAGGTTT\
    TGTTTTGTTATGTTTTTGGTTTATTTTTTGAGGCAGACTCTCACTCGATGTCACCCAGGCTGGAGTGCAGTGGTGCGATC\
    TCGGCTCACTGCAACCTCCACCCCCTGCCTCAGCTTCCTGAATAGCTGGGATTACAGATGACTGCCACTGCACCTGGTTA\
    ATTTTATAATTTTTAGTAGAGACGGGGTTTCACCATCTTGGCCAGGCTGGTATTGAACTCTTGACATTGTGATCCACCTG\
    CCTTGGCCTCCCAAAGTGCTGGGATTACAGGTGTGAGCCACAACACCCGACCAGGTTTTTATTTTGTGGGGGGCTTGTTA\
    TTTCTTGGCCTTACTGATCTTGGCATTTATTTAAAAGGCTTGATAATAACTTATATTGAAGACACTGTTTTACACACACA\
    AATAGTACTCGTTTTCTATTTTTCTGTTCTATATCTTTCTCTGAAAGTAGTTGATCTGTGTTTCTGTAAACAAACTTAAT\
    TCTCTTTAGTTAGGGGACATTTCGAATGTGTGTTTGTAACACTCACCATTTATAAGCAGATTCCAGTAATTTTACATCTA\
    TTTTATTTCACATGAGCAAACTAGTATTACTTATCTCCATTCTTGACTATTTTTAGTGCTTCACAAAATTATAGTCATTT\
    CTATAATAGCTTTATCACTTTTTTTGAGATGCGCAAAAAAGGGATGTTCAGGTAACCATCACATGACAATCATCACATAC\
    CAGTATTTGGCCTTCTTACTGTGAACATTTTCCATTTAAAAAACAAAGTGTACTGCATTAAAACATGCATGAATTTCAGA\
    CTAAATGCCTGCTTATCTACGTCATCAAACCGTTTTTATTATTTATATGTATTAACATTACAGAAACCTGTAATGTCGTA\
    GAACTAATGATAGGTGACATAAATATTTATTGATGTTTTAGTTATAGTTTTCATTTTAGAAAAAAATACAGTAATGTAAA\
    AGGGCATCTGGTTTGGAGTAGATTTGGATAGTAATTAGTATTTTTGCTTTTCCATAAAAATAAATACAAGTTTATAAGTT\
    ACATATATTTTAAATTGTTATTAAACTCAGGTTTCCCAGGTTTTGTGCTCAGTGTTCATTTCAGTTCTTTCTGAAAGGCC\
    CTAGGTTACCTAATTTTGCATTTGACAGAAAGTGCTGTTTCAAATTACTGAATTTTGGTATTGCAGGAAAGACCTGTATG\
    GCAACCTGAAATTGCTTGTACATAATTGCCTTTCAAATTATAGCCCATTAGAAAGAAATGCACCTTTTTTTAGAGCACCT\
    AGGAAAATATTTTCTAGAGAAACTCCTGGTATCAAAATCCCTAAAGCTGTGTGAGCAGCTGGCTCTAAAGGCAGTCACGT\
    CTGGTCCTGGATCGTGTGTATGGCAGCCACACCTGTGTCCCCGGGAAGACATGCTGGTTCTGATACTGGTGTGGGTCGTG\
    TGTATGGCAGCCACACCTGTGTCCCCAGGAAGACATGCTGGTTCTGATACTGGTGGGTCGTGTGTATGGCAGCCACACCT\
    GTGTCCCCAGGAAGACTGCTGGTTCTGATACTGGTGTGGGTCGTGTGTATGGCAGCCACACCTGTGTCCCCAGGAAGACA\
    TGCTGGTTCTGATACTGGTGGGTCGTGTGTATGGCAGCCACACCTGTGTCCCCAGGAAGACATGCTGGTTCTGATACTGG\
    TGGGTCGTGTGTATGGCAGCCACACCTGTGTCCCCAGGAAGACATGCTGGTTCTGATACTGGTGGGTCGTGTGTATGGCA\
    GCCACACCTGTGTCCCCAGGAAGACTGCTGGTTCTGATACTGGTGTGGGTTGTGTGTATGGCAGCCACACCCATGTCCCC\
    AGGAAGACTGCTGGTTCTGATACTGGTGGGTCGTGTGTATGGCAGCCACACCTGTGTCCCCAGGAAGACTGCTGGTTCTG\
    ATACTGGTGTGGGTCGTGTGTATGGCAGCCACACCTGTGCCACATCAGGAAGACATGCTGCTTCTGATACTGGTGAATCT\
    CCCAACCACGTGGAACCACGTGAATTCTCTCCTCATTTTCCCTTTCCTGATCTCAGATTTATGATAGGGAATGAGATCTT\
    CCCTTCCCTATGTTCCTATTGCCCCCATCTCTCTTCTCATCCTTTCATTTGTAAACGAATCAGAAGTCCTGACTTGTGGA\
    AGAGATGCAAGATTCTCCATGTGTGCTACTGATGTGCCTGATCAAGTTAAGTCACCGTTTGGGGGAAGGAGCAGTACTTT\
    TGCTGGTATCATTTACATTTGTACTAACAGGTGAGATATTATCAGAACACACTCTATTATTATTATCAGAGGTGTCTGAT\
    AATGAGATCTTTATAATATGTGATTCAAAGGGGTATGAACACACTAGATGGAGCTTATGAGATGTCAGAAGGAGAGGTAA\
    TGGGATGTCCACGGGGTGAGTTGAATGTGGCGTGAGCACTTAGGGGCTCACTAAAGATGGGACCCAGAACTCAGGCTGCA\
    AAAATGAAGGATAAAGAGTGAAGCTTCTACAGTAAAAGTCAACCTACTTGCATTTACTGAGGGAATAGATAACATAAATA\
    AGTTGTATATGCCAAGACTGGACCTGGTCTAGCTGGGTGTGAACCACAAATGCAGAATTGTGGCTGTTGTAAATAAAGGG\
    AAAGGAGACCCCGACAATCAGCCTCATGAGCGTGGTGTGTGGGATTCTGAATGAATCTGTCCCTCTGGTCAAAATCACTC\
    AAGCATTTATCTGAGCATTTTGCTTGTAGGCATCAGAGCCAGACTATAATTAGAGAAGTTGGAATACGGCCAACAGGATG\
    CCACAGGAAAAATTAAATGCTTGCAAAACACACATTGCAAGAAACAGAGTCTCTTTTCATTGGAAGAGTGAACAGTCACA\
    CTTTTTTTCAGATGGTGCTTGGTTGTGGGAGAAAGGATTGTTAGAACGTGATTGAAAGCCTGTCCAAGGCCCTATACGCA\
    GGGCTCTTCACCTTTGTCTCTGCTGCTCCCGGAGCCATTGCTGACAGGGCTATGAATGACAGCCGTGCTCAGTGGCTTGA\
    CCCCAGGCAGGGCCCAAGGGAGGGGCTCCCTCCCAGGCTGAGTCCAGAGCACTTCAAGCTAGAATGCAGAAAGGGAAGCA\
    CTTACTGTGTAGGCCCTAGAGTCTTCCGACTCTGGACAGAAAATAGAAAAGTGGAACTGAGTTAACTTTACAGCAAGATG\
    CAATGGTGTGTTTGTGAATGGAAAAGTAGAACTGAGCTAACTTTATAAGATGCAATGGTGTGTTCATGGAAATGTTCCAT\
    CTCAGAGGCCTTTCTCAGTGCTCTGATAGGTTTTCTTTTAGTTTATTGAACGGAAGACAGATTTAGTTATAAAAACATGA\
    TCAGCAAGTATGAGCTCTGTCTGCCTCACTGTATCTGAAGTCCCAAGAAGCCACCATTCTGATCTAATCTCTAACGTGGC\
    ACGGGGTGACTGAGGGCCAGGTGGGAGCAGGGCGGAGCCACATAGGCAACACACTTGCGTCTGAGCACTTTCTCAGCTGC\
    TAGGTCCAATTTCTGGTTACACAGATAAGCTTTGGTGAAAGAATAGAACAATTCAAGACATGCCTTTTAGTACATAAATA\
    CAATTGACCATTCTCCTTTAACTGTTAAAAATCCCACTAAATAAATATGATAACACCATCAGTACACATATAATTTATTA\
    AGTACAAATGTGGAGACAAGTTTCAGAAACAATCTTTGATGAATGAGCCATGATTCAGATTTTTAAATCATACCGTATTT\
    GCATTTTAGTTCTATTGTTTTTTCTTTTTGGTTGCTGGTGGCCATGTCTTGTGAGCAGCATAAAAAACTGTGATTGTGAT\
    GTTGCTATTTCTGACCTTGAGGAAAGTTTCAAATATATTTAATTTTCTGTGTATTAATATAAATTAATATAATTGCAGGC\
    TTTTTTTGTTGACATGACTTCAGATTTCATATGAGGTCTGAAAATCTGGTAGTATGCATGAAGTATCATTTTCATTGGAC\
    TTTAATCAATTACTGAAGAGATAAATGCTTATTATCAACTAAAAAACACATTTAAAAAACACATTTTAATTATTAGTAGA\
    TGCGTATTAGTAATTGTAGACCTAGCTGTAGTGAAACTCTGCATTACACTCATTAGGAAAAATTGTGAAGTCCACTTGTA\
    TATAGGCATGCATTTCTTCATATGTATTTTATATTCTCTGAGAAACCGAATATAGACAAAGATGGCATATTTCAAATATT";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_default_contigs_to_their_index() {
        assert_eq!(default_contig_id("chr1"), 0);
        assert_eq!(default_contig_id("chr2"), 1);
    }

    #[test]
    #[should_panic(expected = "unknown contig")]
    fn panics_on_a_contig_outside_the_default_set() {
        let _ = default_contig_id("chrX");
    }

    #[test]
    fn hg38_mini_has_the_two_frozen_contigs() {
        assert_eq!(
            FastaBuilder::hg38_mini().dict(),
            vec![("chr1".to_string(), 10_000), ("chr2".to_string(), 12_000)]
        );
    }

    #[test]
    fn hg38_mini_contigs_are_dna_and_differ_in_gc() {
        let refs = FastaBuilder::hg38_mini();
        let chr1 = refs.bases("chr1", 1, 10_000);
        let chr2 = refs.bases("chr2", 1, 12_000);
        let is_dna = |s: &[u8]| {
            s.iter().all(|&b| matches!(b.to_ascii_uppercase(), b'A' | b'C' | b'G' | b'T'))
        };
        assert!(is_dna(&chr1) && is_dna(&chr2));
        let gc = |s: &[u8]| {
            s.iter().filter(|&&b| matches!(b.to_ascii_uppercase(), b'C' | b'G')).count() * 100
                / s.len()
        };
        // chr1 is the GC-rich slice, chr2 the AT-rich one.
        assert!(gc(&chr1) > 50, "chr1 GC {}", gc(&chr1));
        assert!(gc(&chr2) < 45, "chr2 GC {}", gc(&chr2));
    }

    #[test]
    fn hg38_mini_is_soft_masked_mixed_case() {
        let chr1 = FastaBuilder::hg38_mini().bases("chr1", 1, 10_000);
        assert!(chr1.iter().any(u8::is_ascii_lowercase), "expected soft-masked lowercase bases");
        assert!(chr1.iter().any(u8::is_ascii_uppercase), "expected unmasked uppercase bases");
    }

    #[test]
    fn bases_pads_with_a_past_the_contig_end() {
        let refs = FastaBuilder::new().contig("c", b"ACGT".to_vec());
        assert_eq!(refs.bases("c", 3, 4), b"GTAA".to_vec());
    }

    #[test]
    fn bases_of_an_unknown_contig_is_empty() {
        assert_eq!(FastaBuilder::hg38_mini().bases("chrZ", 1, 10), Vec::<u8>::new());
    }

    #[test]
    fn repeat_tiles_a_motif() {
        assert_eq!(FastaBuilder::new().repeat("c", b"AC", 3).bases("c", 1, 6), b"ACACAC".to_vec());
    }

    #[test]
    fn write_fasta_emits_fasta_and_index() {
        let refs = FastaBuilder::new().contig("c", b"ACGTACGTAC".to_vec());
        let tmp = tempfile::NamedTempFile::with_suffix(".fa").unwrap();
        refs.write_fasta(tmp.path()).unwrap();
        let fasta = std::fs::read_to_string(tmp.path()).unwrap();
        assert!(fasta.starts_with(">c\n"));
        assert!(fasta.contains("ACGTACGTAC"));
        let mut fai = tmp.path().as_os_str().to_owned();
        fai.push(".fai");
        assert!(std::fs::read_to_string(fai).unwrap().starts_with("c\t10\t"));
    }
}
